#!/usr/bin/env node

var semverRegex = require('semver-regex');
var _ = require('lodash');
require('shelljs/global');
var Package = require('./package.json')

var argv = require('minimist')(process.argv.slice(2));

set('-e') // exit on error

if (!process.argv.slice(2).length) {
  console.log();
  console.log('usage: deploy [options]');
  console.log();
  console.log('options: ');
  console.log();
  console.log('-b, --bump <bump> :: Desired bump amount <major, minor, patch>');
  console.log('-s, --silent :: Do not publish to NPM and RubyGems');
  console.log();
  process.exit(0);
}

var type = _.get(argv, 'b', argv.bump);
var silent = _.get(argv, 's', argv.silent)

if (_.isUndefined(type)) {
  console.log('Bump amount required!');
  process.exit(1);
}

console.log('--- Updating NPM Version');
var newVersion = exec('npm version ' + type).output.match(semverRegex())[0].replace(/^(v\.)/,"");

console.log('--- Updating Rails Version');
exec('gem bump --version ' + newVersion);
console.log('--- Building Rails Gem');
exec('gem build egghead-styles.gemspec');

if (!silent) {

}
